version: "3.9"

volumes:
  wazuh-indexer-data:
  wazuh-manager-data:

networks:
  public:
    external: true
  internal:
    external: true

services:
  wazuh_indexer:
    image: wazuh/wazuh-indexer:4.9.2
    environment:
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    sysctls:
      - vm.max_map_count=262144
    volumes:
      - wazuh-indexer-data:/var/lib/wazuh-indexer
    networks:
      - internal
    deploy:
      placement:
        constraints:
          - node.role == worker

  wazuh_manager:
    image: wazuh/wazuh-manager:4.9.2
    environment:
      - WAZUH_INDEXER_URL=https://wazuh_indexer:9200
    ports:
      - "1514:1514/tcp"
      - "1515:1515"
      - "55000:55000"
    volumes:
      - wazuh-manager-data:/var/ossec/data
    networks:
      - internal
    deploy:
      placement:
        constraints:
          - node.role == worker

  wazuh_dashboard:
    image: wazuh/wazuh-dashboard:4.9.2
    networks:
      - internal
      - public
    deploy:
      placement:
        constraints:
          - node.role == worker

