version: "3.9"

volumes:
  wazuh-indexer-data:
  wazuh-manager-data:

networks:
  public:
    external: true
  internal:
    external: true

services:
  wazuh_indexer:
    image: wazuh/wazuh-indexer:4.9.2
    environment:
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - wazuh-indexer-data:/var/lib/wazuh-indexer
    networks:
      - internal
    deploy:
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: on-failure
        max_attempts: 5
        window: 120s

  wazuh_manager:
    image: wazuh/wazuh-manager:4.9.2
    environment:
      - WAZUH_INDEXER_URL=https://wazuh_indexer:9200
    ports:
      - "1514:1514/tcp"
      - "1515:1515"
      - "55000:55000"
    volumes:
      - wazuh-manager-data:/var/ossec/data
    networks:
      - internal
    deploy:
      placement:
        constraints:
          - node.role == worker
      restart_policy:
        condition: on-failure
        max_attempts: 5
        window: 120s

  wazuh_dashboard:
    image: wazuh/wazuh-dashboard:4.9.2
    networks:
      - internal
      - public
    deploy:
      placement:
        constraints:
          - node.role == worker
      labels:
        - traefik.enable=true
        - traefik.http.routers.wazuh.rule=Host(`wazuh.lab`)
        - traefik.http.routers.wazuh.entrypoints=websecure
        - traefik.http.routers.wazuh.tls=true
        - traefik.http.services.wazuh.loadbalancer.server.port=5601
      restart_policy:
        condition: on-failure
        max_attempts: 5
        window: 120s
