all:
  hosts:
    manager:
      ansible_host: 192.168.1.12
      ansible_user: ubuntu
    worker:
      ansible_host: 192.168.1.13
      ansible_user: ubuntu

  children:
    managers:
      hosts:
        manager:
    workers:
      hosts:
        worker
