---
- name: Deploy Wazuh stack to Docker Swarm
  hosts: manager
  become: yes
  vars:
    repo_stack_dir: /opt/mini-soc-stack

  tasks:
    - name: Ensure destination dir exists
      file:
        path: "{{ repo_stack_dir }}"
        state: directory
        owner: "{{ ansible_user }}"
        mode: 0755

    - name: Copy stack files (stack directory)
      copy:
        src: ../../stack/
        dest: "{{ repo_stack_dir }}"
        owner: "{{ ansible_user }}"
        mode: '0644'
      delegate_to: localhost

    - name: Remove previous wazuh stack (ignore failures)
      command: docker stack rm wazuh
      ignore_errors: yes

    - name: Pause briefly for cleanup
      pause:
        seconds: 8

    - name: Deploy updated Wazuh stack
      command: docker stack deploy -c "{{ repo_stack_dir }}/wazuh-stack.yml" wazuh

