name: Mini-SOC CI/CD

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

env:
  DOMAIN: "wazuh.lab"

jobs:
  trivy_scan:
    name: Trivy configuration & image scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run Trivy config scan
        uses: aquasecurity/trivy-action@v0.16.0
        with:
          scan-type: 'fs'
          format: 'table'
          exit-code: '0'
          severity: 'CRITICAL,HIGH'
          ignore-unfixed: true

      - name: Run Trivy image policy checks (local example)
        run: |
          docker pull wazuh/wazuh-indexer:4.9.2 || true
          docker pull wazuh/wazuh-manager:4.9.2 || true
          docker pull wazuh/wazuh-dashboard:4.9.2 || true
          docker run --rm -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy:latest image --severity CRITICAL,HIGH wazuh/wazuh-indexer:4.9.2 || true

  build_and_test:
    name: Tests (Selenium + API)
    runs-on: ubuntu-latest
    needs: trivy_scan
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install test requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r tests/selenium/requirements.txt || pip install selenium requests

      - name: Run API healthcheck tests
        run: pytest -q tests/api/test_healthcheck.py -q || true

      - name: Run Selenium smoke tests (headless)
        run: pytest -q tests/selenium/test_example.py -q || true

  deploy:
    name: Deploy (only on main)
    runs-on: self-hosted
    needs: build_and_test
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run Ansible deploy playbook
        env:
          ANSIBLE_REMOTE_USER: ubuntu
        run: |
          pip install ansible==8.* || true
          ansible-galaxy collection install community.docker --force || true
          ansible-playbook ansible/playbooks/deploy.yml -i ansible/inventories/hosts.yml

