name: Mini-SOC CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  trivy_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run Trivy scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config'
          severity: 'HIGH,CRITICAL'
          exit-code: '1'
          ignore-unfixed: true
          scanners: 'vuln,secret,misconfig,license'
          format: 'table'

  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: self-hosted
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run Ansible Playbook
        run: ansible-playbook ansible/playbooks/deploy.yml

